browser=chrome

db.user=blockuser
db.password=vinciluser
db.serverName=44.217.123.122
db.port=5452
db.dbName=blockreconsit

url=http://44.217.123.122:5000/account/login
username = adithya1@recon.com
password = Adisriram123$

recon_name = autoRecon
recon_id=REC20250725000822999
